name: Metrics

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - "master"
      - "main"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: Shadowghost/gh-metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Shadowghost
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          repositories_affiliations: owner
          config_timezone: Europe/Berlin  
          committer_message: "chore: update metrics"
          retries: 3
          retries_delay: 300
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: true
          plugin_achievements_threshold: B
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_sections: repositories
